name: 🚀 Deploy website on push

on: push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2      
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
      env:
        VITE_CONTENTFUL_SPACE_ID: ${{ secrets.vite_contentful_space_id }}
        VITE_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.vite_contentful_access_token }}
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        PORT: 22
        METHOD: sftp
        FTP_SERVER: home696673610.1and1-data.host
        FTP_USERNAME: ${{ secrets.ftp_username }}
        FTP_PASSWORD: ${{ secrets.ftp_password }}
        LOCAL_DIR: dist/
        REMOTE_DIR: cookbook/
