name: 🚀 Deploy website on push

on: push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2      
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        PORT: 22
        METHOD: sftp
        FTP_SERVER: home696673610.1and1-data.host
        FTP_USERNAME: ${{ secrets.ftp_username }}
        FTP_PASSWORD: ${{ secrets.ftp_password }}
        VITE_CONTENTFUL_SPACE_ID: ${{ secrets.VITE_CONTENTFUL_SPACE_ID }}
        VITE_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.VITE_CONTENTFUL_ACCESS_TOKEN }}
        LOCAL_DIR: dist/
        REMOTE_DIR: cook-book/
